# Generated by Django 5.0.4 on 2024-06-17 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignatura',
            name='nota1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='nota2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='nota3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='nota4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='nota5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='nota6',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='nota7',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='nota8',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='nota9',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='promedio',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
