# Generated by Django 5.0.6 on 2024-06-15 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_asignatura_curso_dia_periodo_user_direccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='periodo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.periodo'),
        ),
    ]
