# Generated by Django 5.0.4 on 2024-06-18 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_asignatura_nota1_asignatura_nota2_asignatura_nota3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignatura',
            name='estudiante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
