# Generated by Django 5.0.4 on 2024-06-06 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_asignatura_curso_dia_periodo_seccion_user_edad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='edad',
        ),
    ]
