# Generated by Django 5.0.4 on 2024-06-15 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_asignatura_curso_dia_periodo_user_direccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodo',
            name='predeterminado',
            field=models.BooleanField(blank=True, default=False, unique=True),
        ),
    ]
