# Generated by Django 5.0.4 on 2024-06-18 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_asignatura_estudiante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignatura',
            name='estudiante',
        ),
        migrations.RemoveField(
            model_name='asignatura',
            name='nota1',
        ),
        migrations.RemoveField(
            model_name='asignatura',
            name='nota2',
        ),
        migrations.RemoveField(
            model_name='asignatura',
            name='nota3',
        ),
        migrations.RemoveField(
            model_name='asignatura',
            name='nota4',
        ),
        migrations.RemoveField(
            model_name='asignatura',
            name='nota5',
        ),
        migrations.RemoveField(
            model_name='asignatura',
            name='nota6',
        ),
        migrations.RemoveField(
            model_name='asignatura',
            name='nota7',
        ),
        migrations.RemoveField(
            model_name='asignatura',
            name='nota8',
        ),
        migrations.RemoveField(
            model_name='asignatura',
            name='nota9',
        ),
        migrations.RemoveField(
            model_name='asignatura',
            name='promedio',
        ),
        migrations.RemoveField(
            model_name='evaluacion',
            name='nombre',
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='nota4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='nota5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='nota6',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='nota7',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='nota8',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='nota9',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
