# Generated by Django 5.0.4 on 2024-06-06 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_remove_user_edad'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='direccion',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='edad',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AddField(
            model_name='user',
            name='telefono',
            field=models.CharField(default='', max_length=10),
        ),
    ]
