# Generated by Django 5.0.4 on 2024-06-10 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_user_direccion_user_edad_user_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='seccion',
            field=models.IntegerField(choices=[(0, 'A'), (1, 'B')]),
        ),
        migrations.DeleteModel(
            name='Seccion',
        ),
    ]
