# Generated by Django 5.0.4 on 2024-06-15 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_alter_periodo_predeterminado'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='periodo',
            constraint=models.UniqueConstraint(condition=models.Q(('predeterminado', True)), fields=('predeterminado',), name='unico_predeterminado'),
        ),
    ]
