# Generated by Django 5.0.4 on 2024-06-27 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_remove_asignatura_estudiante_remove_asignatura_nota1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dia',
        ),
    ]
