# Generated by Django 5.0.4 on 2024-06-15 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_periodo_unico_predeterminado'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='periodo',
            name='unico_predeterminado',
        ),
        migrations.AddConstraint(
            model_name='periodo',
            constraint=models.UniqueConstraint(condition=models.Q(('predeterminado', True)), fields=('nombre', 'predeterminado'), name='unico_predeterminado'),
        ),
    ]
