# Generated by Django 5.0.4 on 2024-06-10 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_alter_curso_seccion_delete_seccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='seccion',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B')], default='A', max_length=2),
        ),
    ]
