# Generated by Django 5.0.4 on 2024-06-12 14:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_alter_curso_seccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='alumnos',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
