# Generated by Django 5.0.6 on 2024-07-01 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_remove_clase_asistencia_asistencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='dia',
            field=models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miercoles', 'Miercoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes')], default='Lunes', max_length=10),
        ),
    ]
