# Generated by Django 5.0.4 on 2024-07-05 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_clase_dia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clase',
            name='hora_inicio',
        ),
        migrations.RemoveField(
            model_name='clase',
            name='hora_termino',
        ),
        migrations.AddField(
            model_name='clase',
            name='hora',
            field=models.CharField(choices=[('08:00', '08:00'), ('08:45', '08:45'), ('10:15', '10:15'), ('11:00', '11:00'), ('11:45', '11:45'), ('12:30', '12:30'), ('13:15', '13:15'), ('14:00', '14:00'), ('14:45', '14:45'), ('15:30', '15:30'), ('16:15', '16:15')], default='8:00', max_length=6),
        ),
    ]
