# Generated by Django 5.0.4 on 2024-07-05 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_remove_clase_hora_inicio_remove_clase_hora_termino_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clase',
            name='dia',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='clase',
            name='hora',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='clase',
            name='nombre',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
