# Generated by Django 5.0.4 on 2024-07-05 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_alter_clase_dia_alter_clase_hora_alter_clase_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clase',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='user',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.curso'),
        ),
    ]
