# Generated by Django 5.0.4 on 2024-06-12 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_alter_user_edad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='edad',
            field=models.CharField(default='', max_length=3),
        ),
    ]
