# Generated by Django 5.0.4 on 2024-06-12 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_alter_user_edad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='curso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='portal.curso'),
        ),
    ]
