# Generated by Django 5.0.4 on 2024-06-12 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_alter_user_curso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='curso',
        ),
        migrations.AddField(
            model_name='user',
            name='curso',
            field=models.ManyToManyField(default='', null=True, to='portal.curso'),
        ),
    ]
