# Generated by Django 5.0.4 on 2024-06-12 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_remove_user_curso_user_curso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='curso',
        ),
        migrations.AddField(
            model_name='user',
            name='curso',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.curso'),
        ),
    ]
